### ISSUE TITLE
Module won't start - testing code committed by accident?

### ISSUE THREAD

**Issue by pieper** [SBU-BMI/SlicerPathology#100]
It looks like some code was added that doesn't belong:
https://github.com/SBU-BMI/SlicerPathology/blame/master/SlicerPathology/SlicerPathology.py#L749-L783

It's leading to the issue described here:

https://discourse.slicer.org/t/pathology-module-install-fail-due-to-slicewidget-attribute-error/2269/4

**Comment by mingrui** [comment]
@pieper 

Please see here, the problem is with indentation, you need to use 4 spaces and indent these lines

https://github.com/SBU-BMI/SlicerPathology/issues/101

**Comment by fedorov** [comment]
@mingrui whether it's dead code, or code that was not properly indented - it must be fixed for the module to be functional.

Hopefully someone from @SBU-BMI/applied-informatics will look into it, or perhaps this module is no longer maintained - I am not sure.

**Comment by fedorov** [comment]
Thanks! I haven't tested the updated code, but I hope it works now!
