### ISSUE TITLE
Fix find children issue

### ISSUE THREAD

**Issue by naucoin** [SBU-BMI/SlicerPathology#11]
In the QuickTCGAEffect:
QuickTCGAEffect.py", line 74, in create
    self.structuresView =
slicer.util.findChildren(slicer.modules.SlicerPathologyWidget.editorWidget.volumes, 'StructuresView')[0]
AttributeError: 'module' object has no attribute 'SlicerPathologyWidget'

There is a slicer pathology attribute on the module object, but I wasn¹t
able to quickly get at the StructuresView child so I¹ll leave that for you
to debug.

**Comment by ebremer** [comment]
This line exists in the code.  I'm not entirely sure what you are asking/commenting on here

**Comment by naucoin** [comment]
It's not working on my build, that line causes the error I included above.

**Comment by ebremer** [comment]
I have not been able to reproduce on Ubuntu platform.

**Comment by naucoin** [comment]
It seems to have been resolved, no longer reproducible on my Mac as well.
