### ISSUE TITLE
github header URL typo

### ISSUE THREAD

**Issue by ihnorton** [SBU-BMI/SlicerPathology#15]
![image](https://cloud.githubusercontent.com/assets/327706/14899601/d2488768-0d5a-11e6-9748-511ac3be1c5a.png)

**Comment by naucoin** [comment]
@ihnorton I'm not spotting it, where is this typo?

**Comment by ihnorton** [comment]
There is an unnecessary **C** at the 6th-to-last character of the URL (red arrow in image above). Only happened to notice when I clicked on the link and it didn't work.

**Comment by naucoin** [comment]
I see the extra C in the URL you pasted above, but I can't find that string in the git checkout of SlicerPathology so I can't figure out where it needs to be changed. Where were you when you clicked on the link?

**Comment by ihnorton** [comment]
It's the header on the repository:

https://github.com/SBU-BMI/SlicerPathology

With sufficient repo privileges (owner? not sure) there should be an "Edit" button next to the banner when you are logged in.

**Comment by naucoin** [comment]
Got it, thanks for the clarification!
