### ISSUE TITLE
User interface and documentation require improvements

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#37]
The following issues must be fixed:

1) the module has 2 effects buttons with identical icons but different panels - please use different icons

2) buttons in the effect panels have no text - please add meaningful text

3) please populate documentation pages so that users of the module not familiar with the functionality could (like me) have a shot at using it: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/SlicerPathology

![image](https://cloud.githubusercontent.com/assets/313942/15016206/03d653a0-11de-11e6-814d-35a48e5ad713.png)

![image](https://cloud.githubusercontent.com/assets/313942/15016211/0b6910ee-11de-11e6-81df-f3ca94cb8b53.png)

![image](https://cloud.githubusercontent.com/assets/313942/15016220/1114de38-11de-11e6-859e-4184a4052d8f.png)

**Comment by ebremer** [comment]
1) Icons different now
2) button texted added
3) initial documentation done
