### ISSUE TITLE
Add meaningful icons

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#38]
Extension icons should be created, and the default icons should be replaced:

https://github.com/SBU-BMI/SlicerPathology/blob/master/SlicerPathology.png
https://github.com/SBU-BMI/SlicerPathology/tree/master/SlicerPathology/Resources/Icons

**Comment by fedorov** [comment]
Would be really nice to have the icons in time for when we present this work in posters, slides and demos on June 13-14 at the face-to-face meeting ...

**Comment by ebremer** [comment]
replaced non-helpful or rough icons

**Comment by fedorov** [comment]
As of today's nightly build of Slicer, the SlicerPathology icon is still the default non-meaningful one.

![image](https://cloud.githubusercontent.com/assets/313942/16430728/1bb8c438-3d4b-11e6-9fff-9b7199018c34.png)

**Comment by ebremer** [comment]
Where is this file stored?  I thought it was stored at the root level of the project in this file:
https://github.com/SBU-BMI/SlicerPathology/blob/master/SlicerPathology.png

**Comment by fedorov** [comment]
It is whatever URL your s4ext points to, but it does point to the right location, so I am not quite sure why it is not updated in the ExtensionManager

https://github.com/Slicer/ExtensionsIndex/blob/master/SlicerPathology.s4ext#L31

**Comment by fedorov** [comment]
for the explanation of the fix, see http://slicer-devel.65872.n3.nabble.com/Extension-icon-does-not-render-in-ExtensionManager-td4036984.html
