### ISSUE TITLE
Manual packaging for Windows and Linux

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#39]
Need to prepare manually packaged Slicer, SlicerOpenCV and SlicerPathology for Linux and Windows to support SBU group, while the dashboard issues are being resolved.

@naucoin would be great if you could work on this

cc: @jcfr

**Comment by jcfr** [comment]
I am currently working on the dashboard.

I gonna manually trigger the build so they are available with the latest nightly. Would that work for you all ?

**Comment by fedorov** [comment]
JC, sure - if this will work, this would be great. This will first give us idea if it builds correctly on all platforms. I was not sure, since SlicerPathology was only built for Mac in the last two days.

**Comment by fedorov** [comment]
There is still the svn not found error for SlicerOpenCV on Windows

http://slicer.cdash.org/viewBuildError.php?buildid=821730

![image](https://cloud.githubusercontent.com/assets/313942/15021564/90937428-11f5-11e6-99ef-c165e3ce8c27.png)

**Comment by naucoin** [comment]
I'll work on getting backup builds ready.

**Comment by jcfr** [comment]
Issue has been identified.

Windows build for SlicerOpenCV, OpenCVExample and SlicerPathology have been restarted ... and packages are now available for all platforms. 

|  | SlicerOpenCV | OpenCVExample | SlicerPathology |
| --- | --- | --- | --- |
| Linux | [link](http://slicer.kitware.com/midas3/slicerappstore?os=linux&arch=amd64&revision=25043&category=&search=OpenCV&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=linux&arch=amd64&revision=25043&category=Examples&search=OpenCVExample&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=linux&arch=amd64&revision=25043&category=&search=SlicerPathology&layout=layout) |
| MacOSX | [link](http://slicer.kitware.com/midas3/slicerappstore?os=macosx&arch=amd64&revision=25043&category=&search=OpenCV&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=macosx&arch=amd64&revision=25043&category=Examples&search=OpenCVExample&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=macosx&arch=amd64&revision=25043&category=&search=SlicerPathology&layout=layout) |
| Windows | [link](http://slicer.kitware.com/midas3/slicerappstore?os=win&arch=amd64&revision=25043&category=&search=OpenCV&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=win&arch=amd64&revision=25043&category=Examples&search=OpenCVExample&layout=layout) | [link](http://slicer.kitware.com/midas3/slicerappstore?os=win&arch=amd64&revision=25043&category=&search=SlicerPathology&layout=layout) |

_Table generated using http://www.tablesgenerator.com/markdown_tables_

**Comment by naucoin** [comment]
Awesome @jcfr , thanks!

**Comment by naucoin** [comment]
On Mac after downloading the Slicer nightly build and installing the SlicerOpenCV and SlicerPathology packages from the above links, on start up I'm getting this error:

`Error(s):
    Cannot load library /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib: (dlopen(/Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib, 5): Library not loaded: @rpath/lib/Slicer-4.5/libvtkSlicerOpenCVModuleLogic.dylib
  Referenced from: /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib
  Reason: image not found)
  Error(s):
    Cannot load library /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerQuickTCGAModule.dylib: (dlopen(/Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerQuickTCGAModule.dylib, 5): Library not loaded: @rpath/lib/Slicer-4.5/libqSlicerQuickTCGAModuleWidgets.dylib
  Referenced from: /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerQuickTCGAModule.dylib
  Reason: image not found)
  Error(s):
    Cannot load library /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerShortCutCoreModule.dylib: (dlopen(/Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerShortCutCoreModule.dylib, 5): Library not loaded: @rpath/lib/Slicer-4.5/libqSlicerShortCutCoreModuleWidgets.dylib
  Referenced from: /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerShortCutCoreModule.dylib
  Reason: image not found)`

**Comment by jcfr** [comment]
> Error(s): Cannot load library

Thanks for the report. I will investigate and report back.

**Comment by naucoin** [comment]
On my mac, reconfiguring and building SlicerOpenCV from scratch, I'm currently stuck at:
`[  7%] Linking CXX shared library ../../lib/Slicer-4.5/qt-loadable-modules/libvtkSlicerOpenCVModuleLogic.dylib
ld: library not found for -lqSlicerBaseQTCLI`
but I think downloading and installing the nightly + some extensions may have left my dev build in an odd state, recompiling.

**Comment by jcfr** [comment]
> library not found for -lqSlicerBaseQTCLI

could you check that your Slicer build contains that library ?

**Comment by naucoin** [comment]
Searching more carefully, something's wrong in my build dir, I have in my Slicer-build dir:
'./bin/libqSlicerBaseQTCLI.dylib
./bin/libqSlicerBaseQTCLIPythonD.dylib
./bin/qSlicerBaseQTCLICxxTests
./bin/qSlicerBaseQTCLIPython.so
./bin/qSlicerBaseQTCLIPythonQt.so'
but also:
'./Slicer-build/bin/libqSlicerBaseQTCLI.dylib
./Slicer-build/bin/libqSlicerBaseQTCLIPythonD.dylib
./Slicer-build/bin/qSlicerBaseQTCLIPython.so
./Slicer-build/bin/qSlicerBaseQTCLIPythonQt.so'

Clean build time!

**Comment by naucoin** [comment]
Clean builds are done. 
SlicerOpenCV: When I do a make package and install from file from the one I built, on restart of the nightly build I get:
`Error(s):
    Cannot load library /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib: (dlopen(/Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib, 5): Library not loaded: @rpath/lib/Slicer-4.5/libvtkSlicerOpenCVModuleLogic.dylib
  Referenced from: /Users/nicole/Desktop/Slicer.app/Contents/Extensions-25043/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules/libqSlicerOpenCVModule.dylib
  Reason: image not found)
`
But if I uninstall the extension and point the Slicer application settings module path to the build directory instead, Slicer starts up properly. Digging into the make package with the logic library.

**Comment by jcfr** [comment]
> re: svn not found error for SlicerOpenCV on Windows

Should be fixed by [r24838](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24838)

**Comment by fedorov** [comment]
👍 @jcfr - svn error is gone

**Comment by jcfr** [comment]
:smile: 

That said .. it broke other extension like SPHARM-PDM . See [here](http://slicer.cdash.org/viewConfigure.php?buildid=822089&status=1). I will fix this.

As a side note, i also started a topic to improve `ctest` so that we can simplify the Slicer extension build system. See https://github.com/Kitware/CMake/compare/master...jcfr:reorganize-cmCTest

**Comment by naucoin** [comment]
@jcfr The latest commit to SlicerOpenCV fixes the error I posted in my last comment.
https://github.com/SBU-BMI/SlicerOpenCV/commit/57045d9a67469ac42a5f0ebe90f871006bd003f4

**Comment by fedorov** [comment]
not needed, since dashboards are working now
