### ISSUE TITLE
duplicate files

### ISSUE THREAD

**Issue by naucoin** [SBU-BMI/SlicerPathology#4]
Clean up of duplicated files:

ShortCut/ShortCutCore/Logic/ShortCut.cpp
QuickTCGAEffect/QuickTCGA/Logic/ShortCut.cpp

ShortCut/ShortCutCore/Logic/ShortCut.h
QuickTCGAEffect/QuickTCGA/Logic/ShortCut.h

ShortCut/ShortCutCore/Logic/utilities.h
QuickTCGAEffect/QuickTCGA/Logic/utilities.h

**Comment by ebremer** [comment]
Resolved.
