### ISSUE TITLE
SlicerPathology not available on Windows

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#47]
As of today, there is no record of SlicerPathology being built on Windows:

http://slicer.cdash.org/index.php?project=Slicer4&date=2016-07-07

It is not clear when this started to happen.

@jcfr any hints on how to debug this?

**Comment by fedorov** [comment]
@ebremer: to clarify, our ability to debug this is complicated because the only way to do this sometime is to physically log into the dashboard machine that exhibits strange behavior. Only @jcfr can do this.

@naucoin: do you still have the setup that allows you to build the extension on Windows? Would it be very hard to check if things work as expected?

**Comment by naucoin** [comment]
@fedorov Yes, I can set off a Slicer build and do SlicerPathology in the morning.
Spoke a bit too soon, the community version of visual studio that I had installed was a time limited free trial, I'll work on getting that updated.
@jcfr posted to the mailing list that the Windows factory machine was going to be offline until at least Monday.

**Comment by fedorov** [comment]
@naucoin any updates on the windows build?

I may be wrong, but I think @jcfr announcement came after I discovered this issue.

**Comment by naucoin** [comment]
Still trying to get Slicer OpenCV to build on windows.

**Comment by fedorov** [comment]
for the reference, issue reported on slicer-devel http://slicer-devel.65872.n3.nabble.com/Extension-problem-Windows-build-is-missing-on-the-dashboard-td4036943.html

**Comment by fedorov** [comment]
@naucoin what is the status of this issue?

**Comment by naucoin** [comment]
Rebuilding again to try and get around a release/debug library problem in getting SlicerOpenCV to build on yaz.

**Comment by fedorov** [comment]
resolved, @naucoin will add details and close

**Comment by naucoin** [comment]
This commit fixes the SlicerOpenCV tests which lets SlicerPathology build on Windows:
https://github.com/Slicer/Slicer/commit/96c1d59ed0b2847e3c526be8063ca786429a92bf
