### ISSUE TITLE
runtime error: cannot write file

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/SlicerPathology#82]
Scenario: We're trying to write a zip file, for the user, to a directory of their choosing.
The procedure works on Linux and Mac, but not Windows.
The problem is, no matter what directory we try to write to on Windows, it doesn't want to write to any of them.  

Let's say we try to write a zip file to the user's home folder.  The zip file gets created, but with zero bytes.

This is the error that occurs:
`UpdateFileList: Failed to create directoryTempWriteoriginal`

It looks like the error is being generated from here: vtkMRMLVolumeArchetypeStorageNode.cxx, but it's not clear **why** it can't create the directory.

Test 1: The user is able to create a directory to their file system outside of Slicer.  Pass.

**Comment by fedorov** [comment]
I don't know. What specific line fails? What is `UpdateFileList`? 

The error message seems to suggest that you are failing to create a directory. Perhaps you are trying to save file to a non-existing directory.

**Comment by tdiprima** [comment]
Hi @fedorov.  It's `UpdateFileList: Failed to create directoryTempWriteoriginal`.

At first, I thought the problem was the misinterpretation of the file path by Windows, as a result of `os.path.join`:
`C:/Users/superbear/Documents\TCGA-94-8490-01Z-00-DX1_45787_50834_500_500_LUSC_gray_20170508082717.zip`

So then, I fixed it (or so I thought) with a `os.path.normpath()` surrounding the `os.path.join`:
`C:/Users/superbear/Documents/TCGA-94-8490-01Z-00-DX1_45787_50834_500_500_LUSC_gray_20170508082717.zip`

But either way, we can't write to the directory.

**Comment by tdiprima** [comment]
> UpdateFileList: Failed to create directoryTempWriteoriginal

Normalizing the path did not resolve the issue.

[PTF:](https://github.com/SBU-BMI/SlicerPathology/blob/master/SlicerPathology/SlicerPathology.py#L332) `sNode.SetDataDirectory(self.dataDirButton.directory`)
Problem now is &ndash; the zip file contains a folder hierarchy for one particular file.  Not a bug, but it's not exactly what we had in mind.

The `permission denied` issue on Windows arises when a user tries to write to the working directory (in this case "Program Files\Slicer...").  So that still needs to be fixed (unless user knows to start Slicer as admin).

**Comment by fedorov** [comment]
Why do you write to working directory? Why not Slicer temporary directory?

**Comment by tdiprima** [comment]
We didn't know any better.  I'll look for an example.
btw... slicer nightly didn't build last night?  it's still showing the old code from May 6th.  Our new code is in v1.2.4, which is in the extensions index.

**Comment by fedorov** [comment]
Here is an example: https://github.com/SlicerProstate/mpReview/blob/master/mpReview.py#L97

Slicer did build last night, and so did your extension. Search for SlicerPathology on this page to confirm: http://slicer.cdash.org/index.php?project=Slicer4&date=2017-05-10.

**Comment by tdiprima** [comment]
Thanks.  
Yes, I misspoke.  Sorry.  Darn it... was hoping you didn't see that yet. :)  Oh well.

**Comment by fedorov** [comment]
No worries! I am happy to help, especially when it's just a quick and easy hint, it's no problem.

**Comment by tdiprima** [comment]
Fixed.  See #83 
Also, the issue from above ("zip file contains folder hierarchy...") is also fixed.
