### ISSUE TITLE
runtime error: permission denied on Windows

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/SlicerPathology#83]
The `permission denied` issue on Windows arises when a user tries to write to the working directory (in this case "Program Files\Slicer...").

Set the default data directory to the user's home folder; not the working directory.

(Will work if user starts Slicer as admin.)

**Comment by fedorov** [comment]
You should always use Slicer temporary directory, and create a sub-directory for your extension, to store any temporary data that is needed by your extension. Slicer temporary directory location is in `slicer.app.temporaryPath`.

xref https://github.com/SBU-BMI/SlicerPathology/issues/82#issuecomment-300777732

**Comment by tdiprima** [comment]
**Fixed.**
1. Using **Slicer temporary directory**, creating sub-directory for our extension
2. `ctkDirectoryButton` &ndash; By default, directory is the current working directory[(*)](http://www.commontk.org/docs/html/classctkDirectoryButton.html).
    - We are setting **default to user's home** directory (*nix & Windows compatible)
